# Generated by Django 2.0.9 on 2018-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
