# Generated by Django 2.0.9 on 2018-11-08 10:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='apply_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='apply_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='apply_grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='apply_possibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='apply_semester',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='client_grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='desire_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='desire_grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='desire_ibt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='desire_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='desire_student',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='desire_types',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('only_male', 'Only-Male'), ('only_female', 'Only-Female'), ('Coed', 'Coed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='eng_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='first_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='gpa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='ibt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='ibtjr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='form'),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='parent_wechat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='sat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='second_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='skype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='third_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='wechat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='arrange_improve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='arrange_per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='class_attendancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='class_attendancy_improve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='conversation_improve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='conversation_per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='culture_adapt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='culture_improve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='rule_improve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='rule_observe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='timestrict_improve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='timestrict_per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
