# Generated by Django 2.0.9 on 2018-12-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181202_1125'),
        ('school', '0017_auto_20181202_1818'),
        ('form', '0002_auto_20181128_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorSellingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('classification', models.CharField(max_length=80, null=True)),
                ('emphasis', models.BooleanField(default=False)),
                ('information', models.CharField(blank=True, max_length=80, null=True)),
                ('evaluation', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Counselor')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
