# Generated by Django 2.0.9 on 2018-11-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181109_1132'),
        ('form', '0002_auto_20181108_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsel',
            old_name='apply_date',
            new_name='counseling_date',
        ),
        migrations.RenameField(
            model_name='counsel',
            old_name='program',
            new_name='program_interested',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='apply_country',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='client',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='client_grade',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_fee',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_grade',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_ibt',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_is_boarding',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_is_communting',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_state',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_student',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='desire_types',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='ibt',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='ibtjr',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='is_formality',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='wechat',
        ),
        migrations.AddField(
            model_name='counsel',
            name='client_class',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='counseler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Counseler'),
        ),
        migrations.AddField(
            model_name='counsel',
            name='current_grade',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='current_school',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='desire_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='expected_departure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='toefl',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='toefljr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='apply_grade',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='apply_possibility',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='eng_level',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='gpa',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='parent_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='parent_wechat',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='sat',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
