# Generated by Django 2.0.9 on 2018-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20181109_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsel',
            name='memo',
        ),
        migrations.AddField(
            model_name='counsel',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
