# Generated by Django 2.0.9 on 2018-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20181110_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsel',
            old_name='apply_possibility',
            new_name='possibility',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='apply_grade',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='apply_semester',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='current_grade',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='current_school',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='eng_level',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='first_date',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='parent_wechat',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='second_date',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='third_date',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='toefl',
        ),
        migrations.RemoveField(
            model_name='counsel',
            name='toefljr',
        ),
        migrations.AddField(
            model_name='counsel',
            name='contact_first',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='contact_second',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsel',
            name='contact_third',
            field=models.DateField(blank=True, null=True),
        ),
    ]
