# Generated by Django 2.0.9 on 2018-11-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20181110_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='contact_first',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='contact_second',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='contact_third',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
