# Generated by Django 2.0.9 on 2018-12-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20181211_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalityfile',
            name='file_source',
            field=models.FileField(blank=True, null=True, upload_to='filebox/students/'),
        ),
    ]
