# Generated by Django 2.0.9 on 2018-12-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20181212_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorsellingpoint',
            name='agent_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselorsellingpoint',
            name='art',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselorsellingpoint',
            name='campus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counselorsellingpoint',
            name='music',
            field=models.TextField(blank=True, null=True),
        ),
    ]
