# Generated by Django 2.0.9 on 2018-11-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20181111_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='counsel_at',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='student',
        ),
        migrations.AddField(
            model_name='formality',
            name='counsel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Counsel'),
        ),
        migrations.AlterField(
            model_name='formality',
            name='air_arrive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='air_arrive_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='air_departure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='air_departure_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='air_ticketing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='apply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='departure_ot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='pickup_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='visa_approve_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='visa_denied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='visa_reserve_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
