# Generated by Django 2.0.9 on 2018-11-13 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20181113_0935'),
        ('form', '0009_auto_20181113_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='formality',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School'),
        ),
    ]
