# Generated by Django 2.0.9 on 2018-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_formality_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='formality',
            name='class_start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='course',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
