# Generated by Django 2.0.9 on 2018-11-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20181113_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formality',
            name='counsel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Counsel'),
        ),
    ]
