# Generated by Django 2.0.9 on 2018-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_auto_20181113_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='class_start_at',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='course',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='school',
        ),
        migrations.AddField(
            model_name='formality',
            name='status',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='class_start_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='course',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='schoolformality',
            name='form_apply_fee',
            field=models.NullBooleanField(),
        ),
    ]
