# Generated by Django 2.0.9 on 2018-11-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_auto_20181113_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='status',
        ),
    ]
