# Generated by Django 2.0.9 on 2018-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_remove_formality_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolformality',
            name='program_fee_complete',
            field=models.NullBooleanField(),
        ),
    ]
