# Generated by Django 2.0.9 on 2018-11-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20181113_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='school_priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='counsel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Counsel'),
        ),
    ]
