# Generated by Django 2.0.9 on 2018-11-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_auto_20181114_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolformality',
            name='formality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_formality', to='form.Formality'),
        ),
    ]
