# Generated by Django 2.0.9 on 2018-11-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_auto_20181114_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formality',
            options={'ordering': ['-created_at']},
        ),
    ]
