# Generated by Django 2.0.9 on 2018-11-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_auto_20181115_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formality',
            options={'ordering': ['created_at']},
        ),
    ]
