# Generated by Django 2.0.9 on 2018-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_auto_20181115_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
