# Generated by Django 2.0.9 on 2018-11-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_schoolformality_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='processing_fee_done',
            field=models.NullBooleanField(),
        ),
    ]
