# Generated by Django 2.0.9 on 2018-11-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_schoolformality_processing_fee_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='formality',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
