# Generated by Django 2.0.9 on 2018-11-19 02:46

from django.db import migrations, models
import django.db.models.deletion
import osc_bge.form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_formality_cancel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('file_source', models.FileField(blank=True, null=True, upload_to=osc_bge.form.models.file_directory_path)),
                ('formality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formality_file', to='form.Formality')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
