# Generated by Django 2.0.9 on 2018-11-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_formalityfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='enrolment_apply_done',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='enrolment_apply_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='prepared_eng_exams',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='prepared_essay',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='prepared_passport',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='prepared_recommendation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='prepared_transcript',
            field=models.NullBooleanField(),
        ),
    ]
