# Generated by Django 2.0.9 on 2018-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_auto_20181122_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='enrolment_apply_done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
