# Generated by Django 2.0.9 on 2018-11-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_schoolformality_enrolment_apply_done_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='school_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='school_interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
