# Generated by Django 2.0.9 on 2018-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_auto_20181122_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='mock_interview',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='school_interview_done',
            field=models.NullBooleanField(),
        ),
    ]
