# Generated by Django 2.0.9 on 2018-11-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_auto_20181122_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='acceptance_letter',
            field=models.NullBooleanField(),
        ),
    ]
