# Generated by Django 2.0.9 on 2018-11-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_auto_20181122_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='cancel_enrolment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
