# Generated by Django 2.0.9 on 2018-11-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_schoolformality_cancel_enrolment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolformality',
            old_name='cancel_enrolment',
            new_name='cancel_enrolment_date',
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='cancel_enrolment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
