# Generated by Django 2.0.9 on 2018-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_auto_20181122_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolformality',
            name='i20_apply_at',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='i20_prefee',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='i20_receive_at',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='i20_restfee',
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='i20_completed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='i20_receipt',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='schoolformality',
            name='i20_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
