# Generated by Django 2.0.9 on 2018-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_auto_20181122_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='i20_copy',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='i20_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='i20_tracking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
