# Generated by Django 2.0.9 on 2018-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_auto_20181122_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolformality',
            name='entrance_approve_at',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='entrance_canceled_at',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='entrance_fee',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='entrance_grade',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='entrance_prefee',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='entrance_restfee',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='form_apply_fee',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='interview_reserve_at',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='program_fee_complete',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='program_fee_send_at',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='program_prefee',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='program_restfee',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='training_reserve_at',
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='bge_program_application',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='financial_support',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='immunization',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='program_fee_completed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='program_fee_receipt',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='provider_application',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='schoolformality',
            name='program_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
