# Generated by Django 2.0.9 on 2018-11-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_auto_20181122_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='visa_reserve_at',
        ),
        migrations.AddField(
            model_name='formality',
            name='visa_reserve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='visa_reserve_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
