# Generated by Django 2.0.9 on 2018-11-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_auto_20181123_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='visa_approve_at',
        ),
        migrations.AddField(
            model_name='formality',
            name='visa_granted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='visa_granted_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
