# Generated by Django 2.0.9 on 2018-11-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_auto_20181123_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='formality',
            name='visa_copy_recieved',
            field=models.NullBooleanField(),
        ),
    ]
