# Generated by Django 2.0.9 on 2018-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_formality_visa_copy_recieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='visa_denied_at',
        ),
        migrations.AddField(
            model_name='formality',
            name='visa_rejected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='visa_rejected_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
