# Generated by Django 2.0.9 on 2018-11-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_auto_20181123_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='air_arrive_at',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='air_departure_at',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='air_ticketing_at',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='departure_complete',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='departure_ot_at',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='pickup_at',
        ),
        migrations.AddField(
            model_name='formality',
            name='air_arrive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='air_arrive_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='air_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='air_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='eticket_attached',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='formality',
            name='air_arrive_port',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='formality',
            name='air_departure_port',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
