# Generated by Django 2.0.9 on 2018-11-23 08:42

from django.db import migrations, models
import django.db.models.deletion
import osc_bge.form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0040_auto_20181123_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationFormality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('with_animal', models.NullBooleanField()),
                ('with_child', models.NullBooleanField()),
                ('with_other_student', models.NullBooleanField()),
                ('other_preference', models.TextField(blank=True, null=True)),
                ('recommendation_a', models.FileField(blank=True, null=True, upload_to=osc_bge.form.models.accommodation_directory_path)),
                ('recommendation_a_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation_b', models.FileField(blank=True, null=True, upload_to=osc_bge.form.models.accommodation_directory_path)),
                ('recommendation_c', models.FileField(blank=True, null=True, upload_to=osc_bge.form.models.accommodation_directory_path)),
                ('recommendation_b_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('host_selection', models.CharField(blank=True, choices=[('a', 'A-Host'), ('b', 'B-Host'), ('c', 'C-Host')], max_length=140, null=True)),
                ('parent_accommodation_guest_num', models.CharField(blank=True, max_length=80, null=True)),
                ('parent_length_of_stay', models.CharField(blank=True, max_length=80, null=True)),
                ('parent_other_preference', models.TextField(blank=True, null=True)),
                ('formality', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodation', to='form.Formality')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
