# Generated by Django 2.0.9 on 2018-11-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_accommodationformality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formality',
            name='is_allergy',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='formality',
            name='is_pet',
        ),
    ]
