# Generated by Django 2.0.9 on 2018-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0042_auto_20181123_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationformality',
            name='application_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationformality',
            name='homestay_recommendation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationformality',
            name='host_selection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodationformality',
            name='parent_accommodation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
