# Generated by Django 2.0.9 on 2018-11-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0043_auto_20181123_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolformality',
            name='departure_confirmed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolformality',
            name='departure_ot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
