# Generated by Django 2.0.9 on 2018-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0044_auto_20181123_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolformality',
            name='departure_confirmed',
        ),
        migrations.RemoveField(
            model_name='schoolformality',
            name='departure_ot',
        ),
        migrations.AddField(
            model_name='formality',
            name='departure_confirmed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formality',
            name='departure_ot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
