# Generated by Django 2.0.9 on 2018-11-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_auto_20181124_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formality',
            name='counsel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formality', to='form.Counsel'),
        ),
    ]
