# Generated by Django 2.0.9 on 2018-11-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0047_auto_20181124_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsel', to='student.Student'),
        ),
    ]
