# Generated by Django 2.0.9 on 2018-11-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0048_auto_20181124_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='counseler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling', to='users.Counseler'),
        ),
    ]
