# Generated by Django 2.0.9 on 2018-11-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybranch',
            name='agency',
        ),
        migrations.DeleteModel(
            name='AgencyBranch',
        ),
    ]
