# Generated by Django 2.0.9 on 2018-12-04 10:44

from django.db import migrations, models
import django.db.models.deletion
import osc_bge.agent.models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('location', models.CharField(blank=True, max_length=140, null=True)),
                ('program', models.CharField(blank=True, max_length=80, null=True)),
                ('commission', models.CharField(blank=True, max_length=140, null=True)),
                ('promotion', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgencyHeadContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('contracted_date', models.DateTimeField(auto_now=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=140, null=True)),
                ('skype', models.CharField(blank=True, max_length=80, null=True)),
                ('wechat', models.CharField(blank=True, max_length=80, null=True)),
                ('location', models.CharField(blank=True, max_length=140, null=True)),
                ('level', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=osc_bge.agent.models.agent_directory_path)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgencyHead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRelationshipHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('writer', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=140, null=True)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('preriod', models.CharField(blank=True, max_length=80, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('summer_camp', models.IntegerField(blank=True, null=True)),
                ('winter_camp', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgencyHead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('preriod', models.CharField(blank=True, max_length=80, null=True)),
                ('college_application', models.IntegerField(blank=True, null=True)),
                ('other_program', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgencyHead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecodnaryProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('preriod', models.CharField(blank=True, max_length=80, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('new_students_fall', models.IntegerField(blank=True, null=True)),
                ('new_students_spring', models.IntegerField(blank=True, null=True)),
                ('total_new_students_bge', models.IntegerField(blank=True, null=True)),
                ('total_students_bge', models.IntegerField(blank=True, null=True)),
                ('terminating_students', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgencyHead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
