# Generated by Django 2.0.9 on 2018-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20181125_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='country',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='program',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='state',
        ),
        migrations.AddField(
            model_name='agency',
            name='branch',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
