# Generated by Django 2.0.9 on 2018-12-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agencyhead_agencyheadcontactinfo_agentrelationshiphistory_camp_collegeapplication_secodnaryprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyhead',
            name='capacity_students',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
