# Generated by Django 2.0.9 on 2018-12-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agencyhead_capacity_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgencyHead'),
        ),
        migrations.AddField(
            model_name='agencyhead',
            name='number_branches',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
