# Generated by Django 2.0.9 on 2018-12-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20181204_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='branch',
        ),
        migrations.AddField(
            model_name='agency',
            name='capacity_students',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='commission',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='location',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='promotion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
