# Generated by Django 2.0.9 on 2018-12-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_auto_20181209_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyBranchProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('program', models.CharField(blank=True, max_length=80, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
