# Generated by Django 2.0.9 on 2018-12-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_agencybranchprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrelationshiphistory',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.AgencyHead'),
        ),
    ]
