# Generated by Django 2.0.9 on 2018-12-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_agentrelationshiphistory_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_branch', to='agent.AgencyHead'),
        ),
    ]
