from django.contrib import admin
from . import models

# Register your models here.
@admin.register(models.School)
class SchoolAdmin(admin.ModelAdmin):

    list_display = (
        "name",
        "lang",
        "sort",
        "is_partner",
        "rank",
        "grade",
        "state",
        "address",
        "student_num",
        "itn_student_num",
        "class_num",
        "offered_grade",
        "semester",
        "religion",
        "types",
        "setting",
        "founded",
        "is_uniform",
        "is_boarding",
        "is_communting",
        "pop_major",
        "rep_major",
        "club_num",
        "honor_process",
        "ap_process",
        "ibt",
        "sat_avg",
        "is_esl",
        "gpa_request",
        "sat_request",
        "program_fee",
        "application_fee",
        "boarding_fee",
        "tenpercent_ratio",
        "ent_approve_ratio",
        "asian_ratio",
        "teacher_student_ratio",
        "fulltime_teacher_ratio",
        "under_twenty_ratio",
        "college_pass_ratio",
        "sat25",
        "sat75",
        "end_ena_deadline",
        "end_ena_noti",
        "application_deadline",
        "files",
    )
