# Generated by Django 2.0.9 on 2018-11-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('detail_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=80, null=True)),
                ('toefl_requirement', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(choices=[('ne', 'NE'), ('se', 'SE'), ('mw', 'MW'), ('w', 'W')], max_length=80, null=True)),
                ('national_univ', models.CharField(choices=[('es', 'Good-Engineering'), ('bs', 'Good-Business'), ('as', 'Good-Art'), ('ss', 'Good-Science'), ('lac', 'Liveral-Arts-College'), ('lc', 'Local-Collge'), ('pu', 'Pathway-University')], max_length=80, null=True)),
                ('tuition', models.IntegerField(blank=True, null=True)),
                ('room_and_board', models.IntegerField(blank=True, null=True)),
                ('sat_act_requirement', models.CharField(blank=True, max_length=80, null=True)),
                ('sat_25', models.CharField(blank=True, max_length=80, null=True)),
                ('sat_75', models.CharField(blank=True, max_length=80, null=True)),
                ('gpa_requirement', models.CharField(blank=True, max_length=80, null=True)),
                ('ranking', models.CharField(blank=True, max_length=80, null=True)),
                ('setting', models.CharField(blank=True, choices=[('urban', 'Urban'), ('Suburban', 'Suburban')], max_length=80, null=True)),
                ('asian_percent', models.IntegerField(blank=True, null=True)),
                ('high_school_10', models.IntegerField(blank=True, null=True)),
                ('full_time_faculty', models.IntegerField(blank=True, null=True)),
                ('student_faculty_ration', models.CharField(blank=True, max_length=80, null=True)),
                ('class_under_20', models.IntegerField(blank=True, null=True)),
                ('ed_ea_deadline', models.DateField(blank=True, null=True)),
                ('ed_ea_noticedate', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('degree_offered', models.CharField(blank=True, max_length=80, null=True)),
                ('most_popular_majors', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('type', models.CharField(choices=[('secondary', 'Secondary'), ('college', 'Collge')], max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='school')),
                ('country', models.CharField(blank=True, choices=[('us', 'US'), ('ca', 'CA'), ('uk', 'UK'), ('au', 'AU'), ('nz', 'NZ')], max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=140, null=True)),
                ('contacts', models.CharField(blank=True, max_length=140, null=True)),
                ('founded', models.CharField(blank=True, max_length=80, null=True)),
                ('transfer', models.BooleanField(default=False)),
                ('term', models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=80, null=True)),
                ('number_students', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('detail_type', models.CharField(choices=[('day_school', 'Day-School'), ('boarding_school', 'Boarding-School'), ('only_boy', 'Only-Boy'), ('only_girl', 'Only-Girl'), ('co_ed', 'Co-ed')], max_length=80, null=True)),
                ('total_fee', models.IntegerField(blank=True, null=True)),
                ('grade_start', models.IntegerField(blank=True, null=True)),
                ('grade_end', models.IntegerField(blank=True, null=True)),
                ('toefl_requirement', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('ma', 'MA'), ('ct', 'CT'), ('nj', 'NJ'), ('pa', 'PA'), ('dc', 'DC'), ('ca', 'CA'), ('fl', 'FL'), ('tx', 'TX'), ('others', 'Others')], max_length=80, null=True)),
                ('number_i18n_students', models.IntegerField(blank=True, null=True)),
                ('program_fee', models.IntegerField(blank=True, null=True)),
                ('number_ap_courses', models.IntegerField(blank=True, null=True)),
                ('number_honor_courses', models.IntegerField(blank=True, null=True)),
                ('number_clubs', models.IntegerField(blank=True, null=True)),
                ('number_sports', models.IntegerField(blank=True, null=True)),
                ('entry_requirement', models.CharField(blank=True, max_length=80, null=True)),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary', to='school.School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='college',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college', to='school.School'),
        ),
    ]
