# Generated by Django 2.0.9 on 2018-11-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('detail_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=80, null=True)),
                ('toefl_requirement', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(choices=[('ne', 'NE'), ('s', 'S'), ('mw', 'MW'), ('w', 'W')], max_length=80, null=True)),
                ('national_univ', models.CharField(choices=[('es', 'Good-Engineering'), ('bs', 'Good-Business'), ('as', 'Good-Art'), ('ss', 'Good-Science'), ('lac', 'Liveral-Arts-College'), ('lc', 'Local-Collge'), ('pu', 'Pathway-University')], max_length=80, null=True)),
                ('tuition', models.IntegerField(blank=True, null=True)),
                ('room_and_board', models.IntegerField(blank=True, null=True)),
                ('sat_act_requirement', models.CharField(blank=True, max_length=80, null=True)),
                ('sat_25', models.CharField(blank=True, max_length=80, null=True)),
                ('sat_75', models.CharField(blank=True, max_length=80, null=True)),
                ('gpa_requirement', models.CharField(blank=True, max_length=80, null=True)),
                ('ranking', models.CharField(blank=True, max_length=80, null=True)),
                ('setting', models.CharField(blank=True, choices=[('urban', 'Urban'), ('Suburban', 'Suburban')], max_length=80, null=True)),
                ('asian_percent', models.IntegerField(blank=True, null=True)),
                ('high_school_10', models.IntegerField(blank=True, null=True)),
                ('full_time_faculty', models.IntegerField(blank=True, null=True)),
                ('student_faculty_ration', models.CharField(blank=True, max_length=80, null=True)),
                ('class_under_20', models.IntegerField(blank=True, null=True)),
                ('ed_ea_deadline', models.DateField(blank=True, null=True)),
                ('ed_ea_noticedate', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('degree_offered', models.CharField(blank=True, max_length=80, null=True)),
                ('most_popular_majors', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_point', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('detail_type', models.CharField(choices=[('day_school', 'Day-School'), ('boarding_school', 'Boarding-School'), ('only_boy', 'Only-Boy'), ('only_girl', 'Only-Girl'), ('co_ed', 'Co-ed')], max_length=80, null=True)),
                ('total_fee', models.IntegerField(blank=True, null=True)),
                ('grade_start', models.IntegerField(blank=True, null=True)),
                ('grade_end', models.IntegerField(blank=True, null=True)),
                ('toefl_requirement', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('ma', 'MA'), ('ct', 'CT'), ('nj', 'NJ'), ('pa', 'PA'), ('dc', 'DC'), ('ca', 'CA'), ('fl', 'FL'), ('tx', 'TX'), ('others', 'Others')], max_length=80, null=True)),
                ('number_i18n_students', models.IntegerField(blank=True, null=True)),
                ('program_fee', models.IntegerField(blank=True, null=True)),
                ('number_ap_courses', models.IntegerField(blank=True, null=True)),
                ('number_honor_courses', models.IntegerField(blank=True, null=True)),
                ('number_clubs', models.IntegerField(blank=True, null=True)),
                ('number_sports', models.IntegerField(blank=True, null=True)),
                ('entry_requirement', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='school',
            name='ap_process',
        ),
        migrations.RemoveField(
            model_name='school',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='school',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='school',
            name='asian_ratio',
        ),
        migrations.RemoveField(
            model_name='school',
            name='boarding_fee',
        ),
        migrations.RemoveField(
            model_name='school',
            name='class_num',
        ),
        migrations.RemoveField(
            model_name='school',
            name='club_num',
        ),
        migrations.RemoveField(
            model_name='school',
            name='college_pass_ratio',
        ),
        migrations.RemoveField(
            model_name='school',
            name='country',
        ),
        migrations.RemoveField(
            model_name='school',
            name='end_ena_deadline',
        ),
        migrations.RemoveField(
            model_name='school',
            name='end_ena_noti',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ent_approve_ratio',
        ),
        migrations.RemoveField(
            model_name='school',
            name='files',
        ),
        migrations.RemoveField(
            model_name='school',
            name='fulltime_teacher_ratio',
        ),
        migrations.RemoveField(
            model_name='school',
            name='gpa_request',
        ),
        migrations.RemoveField(
            model_name='school',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='school',
            name='honor_process',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ibt',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_boarding',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_communting',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_esl',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_partner',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_uniform',
        ),
        migrations.RemoveField(
            model_name='school',
            name='itn_student_num',
        ),
        migrations.RemoveField(
            model_name='school',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='school',
            name='offered_grade',
        ),
        migrations.RemoveField(
            model_name='school',
            name='pop_major',
        ),
        migrations.RemoveField(
            model_name='school',
            name='program_fee',
        ),
        migrations.RemoveField(
            model_name='school',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='school',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='school',
            name='rep_major',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sat25',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sat75',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sat_avg',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sat_request',
        ),
        migrations.RemoveField(
            model_name='school',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='school',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='school',
            name='state',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student_num',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teacher_student_ratio',
        ),
        migrations.RemoveField(
            model_name='school',
            name='tenpercent_ratio',
        ),
        migrations.RemoveField(
            model_name='school',
            name='types',
        ),
        migrations.RemoveField(
            model_name='school',
            name='under_twenty_ratio',
        ),
        migrations.AddField(
            model_name='school',
            name='contacts',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='term',
            field=models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='founded',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School'),
        ),
        migrations.AddField(
            model_name='college',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School'),
        ),
    ]
