# Generated by Django 2.0.9 on 2018-11-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='collge_pass_ratio',
            new_name='college_pass_ratio',
        ),
    ]
