# Generated by Django 2.0.9 on 2018-11-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='location',
            new_name='state',
        ),
    ]
