# Generated by Django 2.0.9 on 2018-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20181128_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(choices=[('us', 'US'), ('ca', 'CA'), ('uk', 'UK'), ('au', 'AU'), ('nz', 'NZ')], max_length=80, null=True),
        ),
    ]
