# Generated by Django 2.0.9 on 2018-11-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20181126_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college', to='school.School'),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary', to='school.School'),
        ),
    ]
