# Generated by Django 2.0.9 on 2018-11-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20181128_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='school',
            old_name='contacts',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='college',
            name='detail_type',
        ),
        migrations.RemoveField(
            model_name='secondary',
            name='detail_type',
        ),
        migrations.RemoveField(
            model_name='secondary',
            name='entry_requirement',
        ),
        migrations.RemoveField(
            model_name='secondary',
            name='toefl_requirement',
        ),
        migrations.RemoveField(
            model_name='secondary',
            name='total_fee',
        ),
    ]
