# Generated by Django 2.0.9 on 2018-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20181126_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.CharField(choices=[('ne', 'NE'), ('se', 'SE'), ('mw', 'MW'), ('w', 'W')], max_length=80, null=True),
        ),
    ]
