# Generated by Django 2.0.9 on 2018-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20181126_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('secondary', 'Secondary'), ('college', 'Collge')], max_length=80, null=True),
        ),
    ]
