# Generated by Django 2.0.9 on 2018-11-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20181130_1342'),
        ('users', '0003_bgebranchcoordinator'),
        ('bge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admission_coordi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_coordi', to='users.BgeBranchCoordinator'),
        ),
        migrations.AddField(
            model_name='school',
            name='partnership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='provider',
            field=models.CharField(blank=True, choices=[('bge', 'BGE'), ('other_providers', 'Other-Provider')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='provider_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bge.BgeBranch'),
        ),
        migrations.AddField(
            model_name='school',
            name='religion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_coordi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_coordi', to='users.BgeBranchCoordinator'),
        ),
        migrations.AddField(
            model_name='school',
            name='web_url',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='accept_12_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondary',
            name='admission_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='admission_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='application_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='avg_sat',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='class_size',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='college_acceptance_rate',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='esl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondary',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='list_ap_courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='list_honor_courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='list_sports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='selling_point',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='student_body',
            field=models.CharField(blank=True, choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coed', 'Coed')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='student_teach_ratio',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='uniform',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='number_ap_courses',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='number_clubs',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='number_honor_courses',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='number_sports',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='schooltypes',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_type', to='school.School'),
        ),
        migrations.AddField(
            model_name='schoolphotos',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_photo', to='school.School'),
        ),
    ]
