# Generated by Django 2.0.9 on 2018-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20181130_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='partnership',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
