# Generated by Django 2.0.9 on 2018-11-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20181126_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, choices=[('us', 'US'), ('ca', 'CA'), ('uk', 'UK'), ('au', 'AU'), ('nz', 'NZ')], max_length=80, null=True),
        ),
    ]
