# Generated by Django 2.0.9 on 2018-11-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20181130_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='area_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
