# Generated by Django 2.0.9 on 2018-11-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_area_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondary',
            old_name='number_i18n_students',
            new_name='international_students',
        ),
    ]
