# Generated by Django 2.0.9 on 2018-11-30 17:58

from django.db import migrations, models
import osc_bge.school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20181130_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=osc_bge.school.models.school_directory_path),
        ),
        migrations.AlterField(
            model_name='schoolphotos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=osc_bge.school.models.school_directory_path),
        ),
    ]
