# Generated by Django 2.0.9 on 2018-12-02 07:25

from django.db import migrations, models
import osc_bge.school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20181201_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondary',
            name='toefl_requirement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=osc_bge.school.models.school_directory_path),
        ),
    ]
