# Generated by Django 2.0.9 on 2018-12-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_auto_20181207_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schools'),
        ),
    ]
