# Generated by Django 2.0.9 on 2018-12-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20181207_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondary',
            name='college_acceptance_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='extra_curricular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='general_impression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='list_clubs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='list_sports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondary',
            name='strong_advantages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
