# Generated by Django 2.0.9 on 2018-12-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_secondary_fee_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/schools/'),
        ),
        migrations.AlterField(
            model_name='schoolphotos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/schools/photos'),
        ),
    ]
