# Generated by Django 2.0.9 on 2018-12-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_auto_20181212_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
