# Generated by Django 2.0.9 on 2018-12-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_auto_20181216_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='student_faculty_ration',
            new_name='student_faculty_ratio',
        ),
    ]
