# Generated by Django 2.0.9 on 2018-12-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_college_acceptance_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='partition',
            new_name='college_type',
        ),
    ]
