# Generated by Django 2.0.9 on 2018-12-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_auto_20181216_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTotalQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('term', models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring')], max_length=80, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
