# Generated by Django 2.0.9 on 2018-12-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_schooltotalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltotalquantity',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tb_of_og', to='school.School'),
        ),
    ]
