# Generated by Django 2.0.9 on 2018-12-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_remove_secondary_accepted_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='program_file',
            field=models.FileField(blank=True, null=True, upload_to='programs/schools/'),
        ),
    ]
