# Generated by Django 2.0.9 on 2018-11-01 13:58

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('users', '0003_auto_20181101_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True)),
                ('birthday', models.DateField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('wechat', models.CharField(max_length=255, null=True)),
                ('skype', models.CharField(max_length=255, null=True)),
                ('major', models.CharField(max_length=255, null=True)),
                ('grade', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('agency_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.AgencyAdminUser')),
                ('agency_branch_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.AgencyBranchAdminUser')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeBranchCoordinator')),
                ('counseler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Counseler')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Host')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Parent')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_school_active', models.BooleanField()),
                ('ibt', models.IntegerField(null=True)),
                ('gpa', models.IntegerField(null=True)),
                ('sat', models.IntegerField(null=True)),
                ('abroad_year', models.DateField(null=True)),
                ('past_eng', models.TextField(null=True)),
                ('past_gpa', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
