# Generated by Django 2.0.9 on 2018-11-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wechat', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=80, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('phone', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('skype', models.CharField(blank=True, max_length=140, null=True)),
                ('wechat', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.CharField(blank=True, choices=[('unregistered', 'Unregistered'), ('registered', 'Registered')], default='unregistered', max_length=80, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('current_grade', models.CharField(blank=True, max_length=80, null=True)),
                ('current_school', models.CharField(blank=True, max_length=140, null=True)),
                ('apply_grade', models.CharField(blank=True, max_length=80, null=True)),
                ('eng_level', models.CharField(blank=True, max_length=140, null=True)),
                ('toefl', models.CharField(blank=True, max_length=80, null=True)),
                ('toefljr', models.CharField(blank=True, max_length=80, null=True)),
                ('gpa', models.CharField(blank=True, max_length=80, null=True)),
                ('sat', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reported_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
