# Generated by Django 2.0.9 on 2018-11-25 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('student', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='counseler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Counseler'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='student.Student'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history', to='student.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='agency_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.AgencyAdminUser'),
        ),
        migrations.AddField(
            model_name='student',
            name='counseler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Counseler'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.ParentInfo'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School'),
        ),
    ]
