# Generated by Django 2.0.9 on 2018-11-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20181130_1342'),
        ('student', '0002_auto_20181128_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStudentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=80, null=True)),
                ('homecity', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
