# Generated by Django 2.0.9 on 2018-11-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20181110_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='current_school',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
