# Generated by Django 2.0.9 on 2018-11-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studenthistory_current_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='gpa',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='sat',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
