# Generated by Django 2.0.9 on 2018-12-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20181208_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('unregistered', 'Unregistered'), ('registered', 'Registered'), ('transferred', 'Transferred'), ('terminated', 'Terminated')], default='unregistered', max_length=80, null=True),
        ),
    ]
