# Generated by Django 2.0.9 on 2018-11-11 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181111_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history', to='student.Student'),
        ),
    ]
