# Generated by Django 2.0.9 on 2018-11-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20181112_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skype',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
