# Generated by Django 2.0.9 on 2018-12-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20181211_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='name',
        ),
    ]
