# Generated by Django 2.0.9 on 2018-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_studentmonthlyreport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('submitted', 'Submiited'), ('manager_confirmed', 'Manager Confirmed'), ('send_to_agent', 'Send to Agent'), ('agent_confirmed', 'Agent Confirmed')], max_length=80, null=True),
        ),
    ]
