# Generated by Django 2.0.9 on 2018-11-15 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history', to='student.Student'),
        ),
    ]
