# Generated by Django 2.0.9 on 2018-12-11 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0012_auto_20181211_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCommunicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('priority', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('manager_confirmed', 'Manager Confirmed'), ('send_to_agent', 'Send to Agent'), ('agent_confirmed', 'Agent Confirmed')], max_length=80, null=True),
        ),
    ]
