# Generated by Django 2.0.9 on 2018-11-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181111_1257'),
        ('student', '0013_auto_20181115_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('counseler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Counseler')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
