# Generated by Django 2.0.9 on 2018-12-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20181211_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmonthlyreport',
            name='report_to_parent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
