# Generated by Django 2.0.9 on 2018-12-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20181213_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='counseling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='manager_confirm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='send_to_agent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
