# Generated by Django 2.0.9 on 2018-12-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20181213_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expense', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
