# Generated by Django 2.0.9 on 2018-12-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_studentaccounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccounting',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting', to='student.Student'),
        ),
    ]
