# Generated by Django 2.0.9 on 2018-12-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20181217_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='bioh_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='bioh_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='bioh_tg',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='chemh_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='chemh_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='chemh_tg',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='cs_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='cs_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='cs_tg',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='eng9h_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='eng9h_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='eng9h_tg',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='geo_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='geo_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='geo_tg',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='orch_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='orch_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='orch_tg',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='precal_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='precal_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='precal_tg',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sp_current',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sp_lv',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sp_tg',
        ),
    ]
