# Generated by Django 2.0.9 on 2018-12-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20181223_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='act',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='sat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmonthlyreport',
            name='toefl',
            field=models.DateField(blank=True, null=True),
        ),
    ]
