# Generated by Django 2.0.9 on 2018-12-23 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20181223_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=80, null=True)),
                ('level', models.CharField(blank=True, max_length=80, null=True)),
                ('target', models.CharField(blank=True, max_length=80, null=True)),
                ('current', models.CharField(blank=True, max_length=80, null=True)),
                ('current_grade', models.CharField(blank=True, max_length=80, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_record', to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='studentmonthlyreport',
            name='quater_gpa',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
