# Generated by Django 2.0.9 on 2018-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20181223_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentacademicrecord',
            name='subject_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
