# Generated by Django 2.0.9 on 2018-12-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_studentacademicrecord_subject_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act_composition_score',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act_eng',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act_math',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act_next_test_date',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act_reading',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act_sci',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='act_target',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sat_evb_reading_writing',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sat_math',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sat_next_test_date',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sat_target',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='sat_total',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl_listening',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl_next_test_date',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl_reading',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl_speaking',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl_target',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl_total',
        ),
        migrations.RemoveField(
            model_name='studentmonthlyreport',
            name='toefl_writing',
        ),
    ]
