# Generated by Django 2.0.9 on 2018-12-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20181224_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('act_date', models.DateField(blank=True, null=True)),
                ('eng', models.CharField(blank=True, max_length=80, null=True)),
                ('math', models.CharField(blank=True, max_length=80, null=True)),
                ('reading', models.CharField(blank=True, max_length=80, null=True)),
                ('science', models.CharField(blank=True, max_length=80, null=True)),
                ('cp_score', models.CharField(blank=True, max_length=80, null=True)),
                ('target', models.CharField(blank=True, max_length=80, null=True)),
                ('next_test_date', models.CharField(blank=True, max_length=80, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act', to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sat_date', models.DateField(blank=True, null=True)),
                ('eb_reading_writing', models.CharField(blank=True, max_length=80, null=True)),
                ('math', models.CharField(blank=True, max_length=80, null=True)),
                ('total', models.CharField(blank=True, max_length=80, null=True)),
                ('target', models.CharField(blank=True, max_length=80, null=True)),
                ('next_test_date', models.CharField(blank=True, max_length=80, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat', to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentToeflHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('toefl_date', models.DateField(blank=True, null=True)),
                ('reading', models.CharField(blank=True, max_length=80, null=True)),
                ('listening', models.CharField(blank=True, max_length=80, null=True)),
                ('speaking', models.CharField(blank=True, max_length=80, null=True)),
                ('writing', models.CharField(blank=True, max_length=80, null=True)),
                ('total', models.CharField(blank=True, max_length=80, null=True)),
                ('target', models.CharField(blank=True, max_length=80, null=True)),
                ('next_test_date', models.CharField(blank=True, max_length=80, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toefl', to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
