# Generated by Django 2.0.9 on 2018-11-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('bge_admin', 'BGE_Admin'), ('bge_team', 'BGE_Team'), ('bge_branch_admin', 'BGE_Branch_Admin'), ('bge_accountant', 'BGE_Accountant'), ('agency_admin', 'Agency_Admin'), ('agency_branch_admin', 'Agency_Branch_Admin'), ('counselor', 'Counselor')], max_length=140, null=True),
        ),
    ]
