# Generated by Django 2.0.9 on 2018-11-01 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('bge', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyAdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyBranchAdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agench_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.AgencyBranch')),
            ],
        ),
        migrations.CreateModel(
            name='BgeAdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('partition', models.CharField(choices=[('entrance', 'ENTRANCE'), ('accounting', 'ACCOUNTING'), ('admin', 'ADMIN')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BgeBranchAdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeAdminUser')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bge.BgeBranch')),
            ],
        ),
        migrations.CreateModel(
            name='BgeBranchCoordinator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[('student_admin', 'STUDENT_ADMIN'), ('school_admin', 'SCHOOL_ADMIN'), ('host_admin', 'HOST_ADMIN')], max_length=255, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bge.BgeBranch')),
                ('branch_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeBranchAdminUser')),
            ],
        ),
        migrations.CreateModel(
            name='Counseler',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.AgencyAdminUser')),
                ('agency_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.AgencyBranchAdminUser')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeBranchCoordinator')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('bge', 'BGE'), ('agency', 'AGENCY')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
