# Generated by Django 2.0.9 on 2018-11-30 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bge', '0001_initial'),
        ('users', '0002_auto_20181129_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgeBranchCoordinator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coordinator', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[('admission_coordi', 'Admission coordinator'), ('school_coordi', 'School coordinator')], max_length=255, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bge.BgeBranch')),
            ],
        ),
    ]
