# Generated by Django 2.0.9 on 2018-11-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181125_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('bge_admin', 'BGE_Admin'), ('agency_admin', 'Agency_Admin'), ('counseler', 'Counseler')], max_length=140, null=True),
        ),
    ]
