# Generated by Django 2.0.9 on 2018-11-01 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181101_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('school', models.CharField(max_length=255, null=True)),
                ('job', models.CharField(max_length=255, null=True)),
                ('employer', models.CharField(max_length=255, null=True)),
                ('is_married', models.BooleanField()),
                ('children', models.IntegerField(null=True)),
                ('pet', models.BooleanField()),
                ('plan', models.TextField(null=True)),
                ('gender_hope', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True)),
                ('student_available', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('filename', models.FileField(null=True, upload_to='host')),
                ('is_deleted', models.BooleanField()),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeBranchCoordinator')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('bge', 'BGE'), ('agency', 'AGENCY'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
