# Generated by Django 2.0.9 on 2018-12-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bgebranchcoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgebranchcoordinator',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_coordi', to='bge.BgeBranch'),
        ),
    ]
