# Generated by Django 2.0.9 on 2018-11-25 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181125_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyadminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agency_admin', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
