# Generated by Django 2.0.9 on 2018-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181125_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('bge_admin', 'BGE_Admin'), ('bge_branch_admin', 'BGE_Branch_Admin'), ('agency_admin', 'Agency_Admin'), ('counseler', 'Counseler')], max_length=140, null=True),
        ),
    ]
