# Generated by Django 2.0.9 on 2018-12-02 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bge', '0001_initial'),
        ('users', '0004_auto_20181202_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgeBranchAdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_admin', to='bge.BgeBranch')),
            ],
        ),
    ]
