# Generated by Django 2.0.9 on 2018-11-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencybranchadminuser',
            old_name='agench_branch',
            new_name='agency_branch',
        ),
    ]
