# Generated by Django 2.0.9 on 2018-11-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181108_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='employer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='host'),
        ),
        migrations.AlterField(
            model_name='host',
            name='gender_hope',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='student_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
