# Generated by Django 2.0.9 on 2018-12-02 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bgebranchadminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgebranchadminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='branch_admin', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
