# Generated by Django 2.0.9 on 2018-11-09 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181108_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseler',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='counseler', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
