# Generated by Django 2.0.9 on 2018-11-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181109_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='images<function user_directory_path at 0x106c24bf8>'),
        ),
    ]
