# Generated by Django 2.0.9 on 2018-12-07 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20181204_1300'),
        ('users', '0007_auto_20181206_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyHeadAdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agency_head_admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agency_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.AgencyHead')),
            ],
        ),
    ]
