# Generated by Django 2.0.9 on 2018-11-09 07:32

from django.db import migrations, models
import osc_bge.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=osc_bge.users.models.user_directory_path),
        ),
    ]
