# Generated by Django 2.0.9 on 2018-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_agencyheadadminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgebranchcoordinator',
            name='position',
            field=models.CharField(choices=[('school_coordi', 'School coordinator'), ('student_coordi', 'Student coordinator'), ('host_coordi', 'Host coordinator')], max_length=255, null=True),
        ),
    ]
