# Generated by Django 2.0.9 on 2018-11-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20181110_1700'),
        ('users', '0009_auto_20181109_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
