# Generated by Django 2.0.9 on 2018-11-11 08:57

from django.db import migrations, models
import osc_bge.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181110_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=osc_bge.users.models.user_directory_path),
        ),
    ]
