# Generated by Django 2.0.9 on 2018-12-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20181202_1125'),
        ('student', '0005_auto_20181203_1208'),
        ('bge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=140, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=140, null=True)),
                ('possible_school', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=140, null=True)),
                ('employer', models.CharField(blank=True, max_length=80, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=80, null=True)),
                ('children', models.CharField(blank=True, max_length=80, null=True)),
                ('pets', models.CharField(blank=True, max_length=80, null=True)),
                ('next_year_plan', models.CharField(blank=True, choices=[('same_student', 'Same-Student'), ('change_student', 'Change-student'), ('na', 'N/A'), ('a', 'A')], max_length=140, null=True)),
                ('student_preference', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=80, null=True)),
                ('hosting_capacity', models.CharField(blank=True, max_length=80, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=80, null=True)),
                ('host_coordi', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeBranchAdminUser')),
                ('provider_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bge.BgeBranch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('host', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.HostFamily')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('host', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.HostFamily')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('host', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.HostFamily')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostStudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, max_length=80, null=True)),
                ('improvement', models.NullBooleanField()),
                ('cultural_fluency', models.TextField(blank=True, null=True)),
                ('house_rule_attitude', models.TextField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('communication', models.TextField(blank=True, null=True)),
                ('sleeping_habits', models.TextField(blank=True, null=True)),
                ('school_attendance', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('host', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.HostFamily')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.HostStudentReport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.HostStudentReport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='host',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.HostFamily'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='writer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeBranchAdminUser'),
        ),
    ]
