# Generated by Django 2.0.9 on 2018-12-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20181205_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostfamily',
            name='host_coordi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BgeBranchCoordinator'),
        ),
        migrations.AlterField(
            model_name='hoststudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='student.Student'),
        ),
    ]
