# Generated by Django 2.0.9 on 2018-12-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20181206_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostfamily',
            name='host_coordi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_coordi', to='users.BgeBranchCoordinator'),
        ),
    ]
