# Generated by Django 2.0.9 on 2018-12-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_remove_communicationlog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoststudent',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='branch.HostFamily'),
        ),
    ]
