# Generated by Django 2.0.9 on 2018-12-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0011_hoststudentreport_host_coordi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoststudentreport',
            name='improvement',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
