# Generated by Django 2.0.9 on 2018-12-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0012_auto_20181210_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoststudentreport',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('complete', 'complete'), ('submitted', 'Submitted')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='hoststudentreport',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
