# Generated by Django 2.0.9 on 2018-12-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0014_auto_20181210_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoststudentreport',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
