# Generated by Django 2.0.9 on 2018-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0015_hoststudentreport_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoststudent',
            name='communication_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
