# Generated by Django 2.0.9 on 2018-12-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bge', '0002_bgevideo'),
        ('branch', '0017_bgeresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgeresource',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bge.BgeBranch'),
        ),
    ]
