# Generated by Django 2.0.9 on 2018-12-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0018_bgeresource_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgeresource',
            old_name='cateogry',
            new_name='category',
        ),
    ]
