# Generated by Django 2.0.9 on 2018-12-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0019_auto_20181213_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoststudentreport',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_report', to='branch.HostFamily'),
        ),
    ]
