# Generated by Django 2.0.9 on 2018-12-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20181212_1532'),
        ('branch', '0020_auto_20181213_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoststudentreport',
            name='student_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_report', to='student.StudentMonthlyReport'),
        ),
    ]
