# Generated by Django 2.0.9 on 2018-12-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0021_hoststudentreport_student_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoststudentreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hosts/students/files/'),
        ),
        migrations.AddField(
            model_name='hoststudentreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hosts/students/photos/'),
        ),
    ]
