# Generated by Django 2.0.9 on 2018-12-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0022_auto_20181224_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoststudentreport',
            name='file',
        ),
        migrations.RemoveField(
            model_name='hoststudentreport',
            name='photo',
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hosts/students/files/'),
        ),
        migrations.AlterField(
            model_name='reportphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hosts/students/photos/'),
        ),
    ]
