# Generated by Django 2.0.9 on 2018-12-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0023_auto_20181224_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='branch.HostStudentReport'),
        ),
        migrations.AlterField(
            model_name='reportphoto',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='branch.HostStudentReport'),
        ),
    ]
