# Generated by Django 2.0.9 on 2019-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0024_auto_20181224_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgeresource',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='bgeresource',
            name='middle_category',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bgeresource',
            name='small_category',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
